In [1]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)

## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [3]:
list_

['1', '2', '3', '4', '5']

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

### Yes, there is a difference in the data type of variables list_ and array_list. list_ is a Python list object while array_list  is a NumPy array object


In [6]:
print(type(list_))

print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


## Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [9]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [10]:
for j in array_list:
    print(type(j))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [11]:
array_list = np.array(object = list_, dtype = int)

In [12]:
array_list

array([1, 2, 3, 4, 5])

In [13]:
for x in list_:
    print(type(x))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [14]:
for y in array_list:
    print(type(y))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


## Consider the below code to answer further questions:

In [16]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [17]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [18]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

## Q4. Write a code to find the following characteristics of variable, num_array:
### (i) shape
### (ii) size

In [20]:
num_array.shape

(2, 3)

In [21]:
num_array.size

6

## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [28]:
zeros_matrix = np.zeros((3,3))
print(zeros_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [31]:
identity_matrix=np.eye(5)

print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
